codecov:
  branch: master

coverage:
  range: "85...100"

  ignore:
    - "docs/*"
    - "tests/*"
    - "cryptoconditions/version.py"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
